### ISSUE TITLE
buy the itg cab?

### ISSUE THREAD

**Issue by ianklatzco** [ddrillini/uiuc-wendy#24]
i believe the rec room 50/50 splits w/ melody.

if we bought it from melody, then we could probably ask for that 50%.

* ask donna how the price breakdown works (is it 50/50)
* ask donna if it would be possible to buy the cab and collect some of the profits for machine parts

**Comment by andrewipark** [comment]
The coin data from 2017 shows, by month (1 is January and 12 is December):
1. **768** (half of winter break, SP17)
2. 1147
3. 2177
4. 1838
5. 1671
6. 1031 (summer break)
7. 1300
8. 1341
9. 2019 (FA17)
10. 1116
11. **2717**
12. 1302

total: 18,427 coins = ~$3,680 at the minimum token price of 20 cents/token. (This is actually a lower bound because prices were slightly higher until FA17.)

**Comment by andrewipark** [comment]
quoth Ian, quoth Donna: probably not happening
