### ISSUE TITLE
Add sanygeol grade glow

### ISSUE THREAD

**Issue by andrewipark** [ddrillini/uiuc-wendy#25]
grades glow on FC (using the strict definition of FC)
this is postponed until after RIP

**Comment by sangyeolbaek** [comment]
Here are the files to change (I labelled the folder to put the files in in the files, since I should not change the file names):

I put a few changes from last time:
- the 1great will always trigger "you tried", but the stars will glow only if no holds/rolls were dropped
- the 1ex will also always trigger "you tried", but the effect will be less dramatic if any holds/rolls were dropped or a mine was hit

thanks

[Grade glow changes.zip](https://github.com/ddrillini/uiuc-wendy/files/1881771/Grade.glow.changes.zip)

**Comment by sangyeolbaek** [comment]
download this one instead; the last one had something wrong
thanks

[Grade glow changes.zip](https://github.com/ddrillini/uiuc-wendy/files/1885852/Grade.glow.changes.zip)

**Comment by andrewipark** [comment]
closing because there's now a PR.

(I'm sorry, I know this is taking forever to handle.)
