### ISSUE TITLE
things to set when we upgrade to SL4.8

### ISSUE THREAD

**Issue by ianklatzco** [ddrillini/uiuc-wendy#50]
https://user-images.githubusercontent.com/1487413/42416503-dd15a428-8224-11e8-9ce8-c35a2a236734.png

multiple scores with same name: off, but willing to discuss
carry combo: on

basically look thru all of these

*Andrew: condensed*

**Comment by ianklatzco** [comment]
make sure percentage scoring is on

**Comment by feedbacker** [comment]
quick dittys:

1. i would love to have multiple high scores with same name OFF. (didn't even know that was a thing.)

here's a scenario where having it ON would be bad for other players that aren't proficient enough on a song:

- Player grinds out an 9~12 range, resulting in multiple (ten to twenty) 98~99%s
- Another player that just got into that difficulty range plays that song
- That other player can't put his/her/their name on it since the leaderboard is filled.
- That other player not only can't track his/her/their progress but also may be discouraged depending on how soft this person is.

2. Is debouncing activated? I didn't know that was a thing in SL and that would be super lovely thing to have given that we have sensors spazzing out. 

I would look thru the settings and have my opinions about it in August, but so far this would be the only thing I have right now.

**Comment by andrewipark** [comment]
Percentage scoring should already be on. I didn't have any issues with changing this manually.
I already set debounce to 30 or 50 ms (forget which).

**Comment by andrewipark** [comment]
Can we set carry combo off? It's honestly kinda distracting... unless that's just UIUC precedent that I wasn't aware of.
I honestly don't care about multiple high scores with same name, but you could just use different characters or change your name, defeating the purpose.

**Comment by ianklatzco** [comment]
@feedbacker +1, seems like we all agree we should have only one entry per tag on the leaderboard. on one hand, it's nice for me to see _when_ i did a high score on a song (look at how much better i am!) but for our machine it's better to have everyone on the leaderboard imo.

@andrewipark imo SOWNDS should still be the default pack. if you agree, let's make sure that's the case

i like carry combo on, because it's fun to have a 2k+ combo + it can be fun to pass a combo around like a hot potato to other people. can it be disabled on a per-profile basis? i'd think not.

i think it's fun, but that's not a strong feeling. if it bugs you, feel free to disable it.

**Comment by andrewipark** [comment]
"default pack" != "enabled packs" in casual mode.
I'll need to look at the Casual mode readme to see how that works

**Comment by feedbacker** [comment]
@andrewipark I have thought about that case where you change name over and over to defeat the leaderboard intentionally, but I decided not to write that since I haven't seen a prick like that play ITG in rec room.

@ianklatzco SOWNDS should be the default pack, but if there's a randomizer function that would preview/select different songs from SOWNDS, that would be lovely. I don't expect that function however.

I also don't mind the carry combo, but I can go either way. I don't have a preference for this and no @andrewipark this is not a UIUC precedent.

**Comment by andrewipark** [comment]
There is a randomizer function. I'll set it to a couple random songs within SOWNDS that are _not_ Applause by Lady Gaga.

**Comment by andrewipark** [comment]
This has been delayed until Dan makes a patch.

**Comment by andrewipark** [comment]
Carry combo is now off (maybe not permanently).
Max high scores on a song now set to 20.
Only one score allowed under a given name now.
Other stuff must wait.

**Comment by ianklatzco** [comment]
don't see anything else needed here so closing
