### ISSUE TITLE
rm spider dance from undertale mods

### ISSUE THREAD

**Issue by ianklatzco** [ddrillini/uiuc-wendy#8]
it's broken, acc to jason, worth a test first but i've seen it broken at least once before, i think.

**Comment by andrewipark** [comment]
Looks like Taro published a version "with crashbug fix", but it doesn't say how long ago, so that version may or may not be on the machine. will check later.

**Comment by andrewipark** [comment]
This is a deliberate 'feature' of the simfile.

In the Lua, there is a condition that if players have elected to kill the muffet a non-zero, even amount of times, then, the next time the simfile is started, a special flag is thrown ("but nobody came") which causes an instafail on the simfile after 10 seconds. The muffet kill counter is incremented (otherwise this logic would always happen after it was triggered). So basically, ever time you kill the muffet after the first time you will get the "but nobody came" glitch.

What should we do about this? It's one thing if that happens on someone's computer (ok, you waste 30 seconds of your time), but when it eats a coin its harder to ignore.

**Comment by ianklatzco** [comment]
modify the simfile or rm it.

preferably modify it, let me ask alan and ping back whether one already exists or not.

**Comment by ianklatzco** [comment]
next you/i are at the machine, add this:

![image](https://user-images.githubusercontent.com/1487413/35492017-d2f3854c-046f-11e8-9459-176f45113764.png)

**Comment by andrewipark** [comment]
Done.

**Comment by ianklatzco** [comment]
thank you! c:
