### ISSUE TITLE
PIUIO driver for windows

### ISSUE THREAD

**Issue by ianklatzco** [ddrillini/uiuc-wendy#82]

**Comment by ianklatzco** [comment]
this now exists, courtesy @dinsfire64. hopefully we can use it for the spring tournament.

**Comment by andrewipark** [comment]
upload to Drive?

**Comment by ianklatzco** [comment]
according to him, the builtin driver in notitg should be able to do it, even for windows.

**Comment by ianklatzco** [comment]
will need to test. i don't have a windows laptop.

can you please install notitg, plug piuio into your laptop, and see if notitg detects the piuio?

https://notitg.heysora.net/

kiah already has it installed, so you could ask to borrow her laptop if you're both there (and practice delegating + teach kiah how it works c:   )

**Comment by DinsFire64** [comment]
So yeah turns out that I didn't need to make that driver and the one in NotITG works fine. Go figure.

So yeah the built in driver works fine for Win 7 Embedded and Win 10, no issues. 

Here are some installation instructions. 

1. Ensure the piuio is getting power on both the jamma edge connector and the USB adapter board from the molex coming off the power supply. 
2. Download and run Zadig
3. Select Cypress EZ-USB FX2 from the list
3a. If it does not appear, click Options > List all Devices
4. Select the WinUSB option from the combo box. 
5. Press the replace driver option. 
6. Wait for the operation to complete. 
7. Open up the Stepmania.ini
8. Find the InputDevices line and set InputDevices=PIUIO
9. Save and start up NotITG
